# Replit deployment configuration
[deployment]
run = ["sh", "-c", "npm run build"]
deploymentTarget = "autoscale"
ignorePorts = false

[nix]
channel = "stable-23_11"

[env]
NODE_ENV = "production"
PATH = "/home/runner/workspace/node_modules/.bin:$PATH"
PULSE_RUNTIME_PATH = "/dev/null"
PULSE_CLIENTCONFIG = "/dev/null"

[[ports]]
localPort = 5000
externalPort = 80

[[ports]]
localPort = 5000
externalPort = 443

[deployment.run]
command = ["sh", "-c", "npm run build"]

[deployment.environment]
NODE_ENV = "production"
PULSE_RUNTIME_PATH = "/dev/null"
PULSE_CLIENTCONFIG = "/dev/null"