# Replit deployment configuration
[deployment]
run = ["sh", "-c", "npm run build && npm run start"]
deploymentTarget = "autoscale"
ignorePorts = false

[nix]
channel = "stable-22_11"

[env]
NODE_ENV = "production"
PATH = "/home/runner/workspace/node_modules/.bin:$PATH"

[[ports]]
localPort = 5000
externalPort = 80

[[ports]]
localPort = 5000
externalPort = 443

[deployment.run]
command = ["sh", "-c", "npm run build && npm run start"]

[deployment.environment]
NODE_ENV = "production"