import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useTheme } from "../contexts/ThemeContext";
import { Radio } from "lucide-react";
import MusicLogoPath from "/MusicLogoIcon.png";
import AdminPanel from "./AdminPanel";
export default function Footer() {
    const { colors, gradient, currentTheme } = useTheme();
    const [isAdminPanelOpen, setIsAdminPanelOpen] = useState(false);
    const scrollToSection = (sectionId) => {
        const element = document.getElementById(sectionId);
        if (element) {
            element.scrollIntoView({ behavior: "smooth" });
        }
    };
    return (_jsxs("footer", { className: "py-12 transition-colors duration-300", style: { backgroundColor: colors.background }, children: [_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-8", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-4 mb-4", children: [_jsx("div", { className: "flex items-center justify-center w-8 h-8 rounded-full", style: {
                                                    background: gradient,
                                                    padding: '5px'
                                                }, children: _jsx("img", { src: MusicLogoPath, alt: "Music Logo", className: "w-full h-full object-contain" }) }), _jsxs("div", { className: "flex flex-col", children: [_jsx("div", { className: "text-sm font-black leading-tight", style: {
                                                            color: currentTheme === 'light-mode' ? '#000000' : colors.text
                                                        }, children: "SPANDEX SALVATION" }), _jsx("div", { className: "text-sm font-black leading-tight", style: { color: colors.primary }, children: "RADIO" })] })] }), _jsx("p", { className: "text-sm", style: { color: colors.textMuted }, children: "Your home for old-school metal music. Broadcasting the rebellion since 2025." }), _jsx("button", { onClick: () => window.open('mailto:support@spandexsalvationradio.com', '_blank'), className: "text-sm transition-colors duration-300 block mt-2 text-left p-0 m-0 bg-transparent border-0 cursor-pointer focus:outline-none focus:ring-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Email Support" })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold mb-4", style: {
                                            color: currentTheme === 'light-mode' ? '#000000' : colors.text
                                        }, children: "Quick Links" }), _jsxs("ul", { className: "space-y-3 text-sm", children: [_jsx("li", { children: _jsx("button", { onClick: () => scrollToSection("hero"), className: "transition-colors text-left block p-0 m-0 bg-transparent focus:outline-none focus:ring-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Home" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection("schedule"), className: "transition-colors text-left block p-0 m-0 bg-transparent border-0 focus:outline-none focus:ring-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Schedule" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection("submissions"), className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Submissions" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection("contact"), className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Contact" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection("subscribe"), className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Subscribe" }) })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold mb-4", style: {
                                            color: currentTheme === 'light-mode' ? '#000000' : colors.text
                                        }, children: "Support" }), _jsxs("ul", { className: "space-y-3 text-sm", children: [_jsx("li", { children: _jsx("button", { onClick: () => window.location.href = "/help", className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Help Center" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection("contact"), className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Technical Support" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection("submissions"), className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Submit Songs" }) }), _jsx("li", { children: _jsx("button", { onClick: () => window.location.href = "/guidelines", className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Community Guidelines" }) }), _jsx("li", { children: _jsx("button", { onClick: () => window.location.href = "/privacy", className: "transition-colors text-left block p-0 m-0 bg-transparent border-0", style: { color: colors.textMuted }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = colors.textMuted, children: "Privacy Policy" }) })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold mb-4", style: {
                                            color: currentTheme === 'light-mode' ? '#000000' : colors.text
                                        }, children: "Stream Info" }), _jsxs("ul", { className: "space-y-3 text-sm", children: [_jsx("li", { children: _jsxs("div", { className: "flex items-center", style: { color: colors.textMuted }, children: [_jsx("span", { className: "mr-3 flex-shrink-0", style: { color: colors.primary }, children: _jsx(Radio, { className: "h-4 w-4" }) }), _jsx("span", { children: "24/7 Live Stream" })] }) }), _jsx("li", { children: _jsxs("div", { className: "flex items-center", style: { color: colors.textMuted }, children: [_jsx("span", { className: "mr-3 flex-shrink-0 text-center w-4", style: { color: colors.primary }, children: "\u266A" }), _jsx("span", { children: "320kbps Quality" })] }) }), _jsx("li", { children: _jsxs("div", { className: "flex items-center", style: { color: colors.textMuted }, children: [_jsx("span", { className: "mr-3 flex-shrink-0 text-center w-4", style: { color: colors.primary }, children: "\uD83C\uDF0D" }), _jsx("span", { children: "Global Coverage" })] }) }), _jsx("li", { children: _jsxs("div", { className: "flex items-center", style: { color: colors.textMuted }, children: [_jsx("span", { className: "mr-3 flex-shrink-0 text-center w-4", style: { color: colors.primary }, children: "\uD83D\uDEE1\uFE0F" }), _jsx("span", { children: "Secure & Reliable" })] }) })] })] })] }), _jsx("div", { className: "pt-8", children: _jsxs("div", { className: "flex flex-wrap items-center justify-center md:justify-between gap-6 text-sm", children: [_jsx("div", { className: "font-semibold", style: {
                                        color: currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted
                                    }, children: "\u00A9 2025 Spandex Salvation Radio. All rights reserved." }), _jsx("a", { href: "/terms", className: "font-semibold transition-colors duration-300", style: {
                                        color: currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted
                                    }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted, children: "Terms of Service" }), _jsx("a", { href: "/privacy", className: "font-semibold transition-colors duration-300", style: {
                                        color: currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted
                                    }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted, children: "Privacy Policy" }), _jsx("a", { href: "/cookies", className: "font-semibold transition-colors duration-300", style: {
                                        color: currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted
                                    }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted, children: "Cookies" }), _jsx("button", { onClick: () => setIsAdminPanelOpen(true), className: "font-semibold transition-colors duration-300 bg-transparent border-0 p-0 focus:outline-none focus:ring-0", style: {
                                        color: currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted
                                    }, onMouseEnter: (e) => e.currentTarget.style.color = colors.primary, onMouseLeave: (e) => e.currentTarget.style.color = currentTheme === 'light-mode' ? 'rgba(0, 0, 0, 0.7)' : colors.textMuted, children: "Admin" })] }) })] }), isAdminPanelOpen && (_jsx(AdminPanel, { onClose: () => setIsAdminPanelOpen(false) }))] }));
}
